{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a3703804",
   "metadata": {},
   "source": [
    "CUSTOMER CHURN ANALYSIS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "afd07b6f",
   "metadata": {},
   "source": [
    "Imported necessary python libraries"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0be8aba2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>customerID</th>\n",
       "      <th>gender</th>\n",
       "      <th>SeniorCitizen</th>\n",
       "      <th>Partner</th>\n",
       "      <th>Dependents</th>\n",
       "      <th>tenure</th>\n",
       "      <th>PhoneService</th>\n",
       "      <th>MultipleLines</th>\n",
       "      <th>InternetService</th>\n",
       "      <th>OnlineSecurity</th>\n",
       "      <th>...</th>\n",
       "      <th>DeviceProtection</th>\n",
       "      <th>TechSupport</th>\n",
       "      <th>StreamingTV</th>\n",
       "      <th>StreamingMovies</th>\n",
       "      <th>Contract</th>\n",
       "      <th>PaperlessBilling</th>\n",
       "      <th>PaymentMethod</th>\n",
       "      <th>MonthlyCharges</th>\n",
       "      <th>TotalCharges</th>\n",
       "      <th>Churn</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>7590-VHVEG</td>\n",
       "      <td>Female</td>\n",
       "      <td>0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>DSL</td>\n",
       "      <td>No</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Month-to-month</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Electronic check</td>\n",
       "      <td>29.85</td>\n",
       "      <td>29.85</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>5575-GNVDE</td>\n",
       "      <td>Male</td>\n",
       "      <td>0</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>34</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>DSL</td>\n",
       "      <td>Yes</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>One year</td>\n",
       "      <td>No</td>\n",
       "      <td>Mailed check</td>\n",
       "      <td>56.95</td>\n",
       "      <td>1936.30</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3668-QPYBK</td>\n",
       "      <td>Male</td>\n",
       "      <td>0</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>2</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>DSL</td>\n",
       "      <td>Yes</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Month-to-month</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Mailed check</td>\n",
       "      <td>53.85</td>\n",
       "      <td>107.70</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>7795-CFOCW</td>\n",
       "      <td>Male</td>\n",
       "      <td>0</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>45</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>DSL</td>\n",
       "      <td>Yes</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>One year</td>\n",
       "      <td>No</td>\n",
       "      <td>Bank transfer (automatic)</td>\n",
       "      <td>42.30</td>\n",
       "      <td>1903.50</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>4 rows × 21 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \\\n",
       "0  7590-VHVEG  Female              0     Yes         No       1           No   \n",
       "1  5575-GNVDE    Male              0      No         No      34          Yes   \n",
       "2  3668-QPYBK    Male              0      No         No       2          Yes   \n",
       "3  7795-CFOCW    Male              0      No         No      45           No   \n",
       "\n",
       "  MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \\\n",
       "0            No             DSL             No  ...               No   \n",
       "1            No             DSL            Yes  ...              Yes   \n",
       "2            No             DSL            Yes  ...               No   \n",
       "3            No             DSL            Yes  ...              Yes   \n",
       "\n",
       "  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \\\n",
       "0          No          No              No  Month-to-month              Yes   \n",
       "1          No          No              No        One year               No   \n",
       "2          No          No              No  Month-to-month              Yes   \n",
       "3         Yes          No              No        One year               No   \n",
       "\n",
       "               PaymentMethod MonthlyCharges  TotalCharges  Churn  \n",
       "0           Electronic check          29.85         29.85     No  \n",
       "1               Mailed check          56.95       1936.30     No  \n",
       "2               Mailed check          53.85        107.70    Yes  \n",
       "3  Bank transfer (automatic)          42.30       1903.50     No  \n",
       "\n",
       "[4 rows x 21 columns]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv(\"CustomerChurn.csv\")\n",
    "df.head(4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d6e5d25c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "customerID           object\n",
       "gender               object\n",
       "SeniorCitizen         int64\n",
       "Partner              object\n",
       "Dependents           object\n",
       "tenure                int64\n",
       "PhoneService         object\n",
       "MultipleLines        object\n",
       "InternetService      object\n",
       "OnlineSecurity       object\n",
       "OnlineBackup         object\n",
       "DeviceProtection     object\n",
       "TechSupport          object\n",
       "StreamingTV          object\n",
       "StreamingMovies      object\n",
       "Contract             object\n",
       "PaperlessBilling     object\n",
       "PaymentMethod        object\n",
       "MonthlyCharges      float64\n",
       "TotalCharges        float64\n",
       "Churn                object\n",
       "dtype: object"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.dtypes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d5676aa8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "customerID          0\n",
      "gender              0\n",
      "SeniorCitizen       0\n",
      "Partner             0\n",
      "Dependents          0\n",
      "tenure              0\n",
      "PhoneService        0\n",
      "MultipleLines       0\n",
      "InternetService     0\n",
      "OnlineSecurity      0\n",
      "OnlineBackup        0\n",
      "DeviceProtection    0\n",
      "TechSupport         0\n",
      "StreamingTV         0\n",
      "StreamingMovies     0\n",
      "Contract            0\n",
      "PaperlessBilling    0\n",
      "PaymentMethod       0\n",
      "MonthlyCharges      0\n",
      "TotalCharges        0\n",
      "Churn               0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(df.isnull().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "cb57540e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "True\n"
     ]
    }
   ],
   "source": [
    "df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors=\"coerce\")\n",
    "for i in range(0,len(df)):\n",
    "    df.loc[i,'TotalCharges']=(df.loc[i,\"tenure\"]*df.loc[i,\"MonthlyCharges\"])\n",
    "if ((df[\"tenure\"]*df[\"MonthlyCharges\"])==df['TotalCharges']).all():\n",
    "    print(\"True\")\n",
    "else:\n",
    "    print(\"False\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "ac749401",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>customerID</th>\n",
       "      <th>gender</th>\n",
       "      <th>SeniorCitizen</th>\n",
       "      <th>Partner</th>\n",
       "      <th>Dependents</th>\n",
       "      <th>tenure</th>\n",
       "      <th>PhoneService</th>\n",
       "      <th>MultipleLines</th>\n",
       "      <th>InternetService</th>\n",
       "      <th>OnlineSecurity</th>\n",
       "      <th>...</th>\n",
       "      <th>DeviceProtection</th>\n",
       "      <th>TechSupport</th>\n",
       "      <th>StreamingTV</th>\n",
       "      <th>StreamingMovies</th>\n",
       "      <th>Contract</th>\n",
       "      <th>PaperlessBilling</th>\n",
       "      <th>PaymentMethod</th>\n",
       "      <th>MonthlyCharges</th>\n",
       "      <th>TotalCharges</th>\n",
       "      <th>Churn</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>7590-VHVEG</td>\n",
       "      <td>Female</td>\n",
       "      <td>0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>DSL</td>\n",
       "      <td>No</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Month-to-month</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Electronic check</td>\n",
       "      <td>29.85</td>\n",
       "      <td>29.85</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>5575-GNVDE</td>\n",
       "      <td>Male</td>\n",
       "      <td>0</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>34</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>DSL</td>\n",
       "      <td>Yes</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>One year</td>\n",
       "      <td>No</td>\n",
       "      <td>Mailed check</td>\n",
       "      <td>56.95</td>\n",
       "      <td>1936.30</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3668-QPYBK</td>\n",
       "      <td>Male</td>\n",
       "      <td>0</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>2</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>DSL</td>\n",
       "      <td>Yes</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Month-to-month</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Mailed check</td>\n",
       "      <td>53.85</td>\n",
       "      <td>107.70</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>7795-CFOCW</td>\n",
       "      <td>Male</td>\n",
       "      <td>0</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>45</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>DSL</td>\n",
       "      <td>Yes</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>One year</td>\n",
       "      <td>No</td>\n",
       "      <td>Bank transfer (automatic)</td>\n",
       "      <td>42.30</td>\n",
       "      <td>1903.50</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>9237-HQITU</td>\n",
       "      <td>Female</td>\n",
       "      <td>0</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>2</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>Fiber optic</td>\n",
       "      <td>No</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Month-to-month</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Electronic check</td>\n",
       "      <td>70.70</td>\n",
       "      <td>141.40</td>\n",
       "      <td>Yes</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 21 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \\\n",
       "0  7590-VHVEG  Female              0     Yes         No       1           No   \n",
       "1  5575-GNVDE    Male              0      No         No      34          Yes   \n",
       "2  3668-QPYBK    Male              0      No         No       2          Yes   \n",
       "3  7795-CFOCW    Male              0      No         No      45           No   \n",
       "4  9237-HQITU  Female              0      No         No       2          Yes   \n",
       "\n",
       "  MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \\\n",
       "0            No             DSL             No  ...               No   \n",
       "1            No             DSL            Yes  ...              Yes   \n",
       "2            No             DSL            Yes  ...               No   \n",
       "3            No             DSL            Yes  ...              Yes   \n",
       "4            No     Fiber optic             No  ...               No   \n",
       "\n",
       "  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \\\n",
       "0          No          No              No  Month-to-month              Yes   \n",
       "1          No          No              No        One year               No   \n",
       "2          No          No              No  Month-to-month              Yes   \n",
       "3         Yes          No              No        One year               No   \n",
       "4          No          No              No  Month-to-month              Yes   \n",
       "\n",
       "               PaymentMethod MonthlyCharges  TotalCharges  Churn  \n",
       "0           Electronic check          29.85         29.85     No  \n",
       "1               Mailed check          56.95       1936.30     No  \n",
       "2               Mailed check          53.85        107.70    Yes  \n",
       "3  Bank transfer (automatic)          42.30       1903.50     No  \n",
       "4           Electronic check          70.70        141.40    Yes  \n",
       "\n",
       "[5 rows x 21 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Electronic check' 'Mailed check' 'Bank transfer (automatic)'\n",
      " 'Credit card (automatic)']\n",
      "['Month-to-month' 'One year' 'Two year']\n",
      "1\n",
      "72\n"
     ]
    }
   ],
   "source": [
    "print(df['PaymentMethod'].unique())\n",
    "print(df['Contract'].unique())\n",
    "print(df['tenure'].min())\n",
    "print(df['tenure'].max())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "f0cbc63a",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = df.drop(df[df['tenure'] == 0].index, axis=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "cc88bb95",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"MultipleLines\"] = df[\"MultipleLines\"].replace(\"No phone service\", \"No\")\n",
    "df[\"OnlineSecurity\"] = df[\"OnlineSecurity\"].replace(\"No internet service\", \"No\")\n",
    "df[\"OnlineBackup\"] = df[\"OnlineBackup\"].replace(\"No internet service\", \"No\")\n",
    "df[\"DeviceProtection\"] = df[\"DeviceProtection\"].replace(\"No internet service\", \"No\")\n",
    "df[\"TechSupport\"] = df[\"TechSupport\"].replace(\"No internet service\", \"No\")\n",
    "df[\"StreamingTV\"] = df[\"StreamingTV\"].replace(\"No internet service\", \"No\")\n",
    "df[\"StreamingMovies\"] = df[\"StreamingMovies\"].replace(\"No internet service\", \"No\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "a779de8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv(\"CustomerChurn.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "01de861e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total: 7032\n",
      "Yes: 73.42%, 5163\n",
      " No: 26.58%, 1869\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAkQAAAHHCAYAAABeLEexAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjYsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvq6yFwwAAAAlwSFlzAAAPYQAAD2EBqD+naQAALX5JREFUeJzt3QmczfX+x/HPjDELGvsaxpRirBMKt80+oW6ihSRZKkKh8J+brN24yr6ksnblihYVsm8VimEiWxSXYgxpDC5mjPk/Pt/H43ce58yMMaPhnJnv6/l4/B5nzu/3Pb/z/R3Lec93+/mlpqamCgAAgMX8vV0BAAAAbyMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABFhg2bJj4+fndlPdq1KiR2Rzr16837/3JJ5/clPd/7rnnpFKlSuLLzp07J927d5cyZcqYz6Zv3745+ud86tSpHDkfYBMCEZDLzJkzx3zpOVtwcLCUK1dOoqKiZNKkSXL27NkceZ9jx46ZL9jY2FjxNb5ct6x46623zJ9jz5495d///rd06tQp0/IpKSkye/ZsEzSLFSsmQUFBJvR16dJFtm3bdtPqDeRlAd6uAIDrM2LECAkPD5fk5GSJi4szLTHa0jBu3Dj58ssvpVatWq6ygwcPlv/7v//LdugYPny4+eKNjIzM8utWrlwpN1pmdfvggw/kypUr4svWrl0rDRo0kKFDh16z7IULF6Rt27ayfPlyeeCBB+Qf//iHCUWHDx+WhQsXyty5c+XIkSNSvnz5m1J3IK8iEAG5VMuWLaVevXqu59HR0eaL9uGHH5a///3vsnfvXgkJCTHHAgICzHYj/e9//5MCBQpIYGCgeFP+/PnF18XHx0u1atWyVHbAgAEmDI0fPz5d15oGKt1/s50/f14KFix4098XuJHoMgPykCZNmsgbb7wh//3vf2XevHmZjiFatWqV3HfffVKkSBEpVKiQVKlSxbQ+KG1tuvvuu83P2i3jdM9pN4/SrpsaNWpITEyMabXQIOS8Nu0YIvduHy2j42b0y1RD29GjRz3KaIuPjgFKy/2c16pbRmOI9Av81VdflQoVKpjuJr3Wd955R1JTUz3K6Xl69+4tixcvNtenZatXr24CSVaDTrdu3aR06dKmK7N27dqmBSfteKpDhw7J0qVLXXXX1p6M/Pbbb/Lee+9J8+bNMxxnlC9fPnnttdfStQ4lJCSYz0H/bAsXLmw+Jw2sDn0/988s7Wegf1/S/t3Zs2ePPP3001K0aFHz90bp56wB/Ntvv5V77rnHXPNtt90mH374YZY+L8CXEIiAPMYZj5JZ19Xu3bvNF9mlS5dM19vYsWNNQPnuu+/M8YiICLNfvfDCC2aci24afhx//PGHaaXSLqsJEyZI48aNM63XP//5TxMCBg0aJC+//LIJZM2aNTNdQtmRlbq509Cj16YtKQ899JDpUtRApC0v/fv3T1dev9xfeuklad++vYwZM0YuXrwo7dq1M9ebGb0ODW1al44dO8rbb79twogGk4kTJ7rqrsdLlChhPjen7iVLlszwnF9//bVcvnz5mmOM0nryySfNWLJRo0aZnzX4aBfjX/HEE0+YUKXjn55//nnX/oMHD8rjjz9uQpv+PdLApNesf8eAXCUVQK4ye/ZsbdZI3bp161XLFC5cOPWuu+5yPR86dKh5jWP8+PHm+cmTJ696Dj2/ltH3S+vBBx80x6ZPn57hMd0c69atM2VvvfXW1MTERNf+hQsXmv0TJ0507QsLC0vt3LnzNc+ZWd309Xoex+LFi03ZN99806Pc448/nurn55d68OBB1z4tFxgY6LHvxx9/NPsnT56cmpkJEyaYcvPmzXPtS0pKSm3YsGFqoUKFPK5d69e6devUa+nXr585544dO1Kzwvlz7tq1q8f+xx57LLV48eKu54cOHbrq56f79Txpz9mhQ4d0ZfU69NjGjRtd++Lj41ODgoJSX3311SzVGfAVtBABeZB2gWU220y7UtQXX3xx3QOQtTtJu2Ky6tlnn5VbbrnF9VxbFcqWLSvLli2TG0nPr11L2irlTrvQ9PtfW2HcaavV7bff7nqug9NDQ0Pl119/veb7aHdghw4dPMYz6fvqNPsNGzZku+6JiYnm0f1zy4oePXp4PL///vtNC5dzvuuR9pwOHQul53doa5e2wF3r8wJ8DYEIyIP0CzizL9GnnnpK7r33XrMWjo530e4hnbGUnXB06623ZmsA9R133OHxXMelVK5c+arjZ3KKjqfSZQnSfh7afeUcd1exYsV059BuoD///POa76PX6O/vn6X3yQoNYiq7SymkvQatv7rWNWRGZzRm5b2c9/sr7wV4A4EIyGN0IO6ZM2dM2LganX22ceNGWb16tRmfsnPnThOSdByIDn7OCmcGW0662uKRWa1TTtDWpIykHYB9M1StWtU87tq1K0ev4Xo+56v9efvS5wX8FQQiII/RQbpKF2rMjLZkNG3a1Awy1hlEOuhZp+2vW7fOHM/pla0PHDiQ7gtTB+S6zwjTlgWdIZVW2taV7NQtLCzMrFuUtpVl3759ruM5Qc+j15i2le2vvI8OWtfA4T5jMCc4LUZpP+vracUC8goCEZCHaKAZOXKk6d7QmU5Xc/r06XT7nAUOdeaZctaZySigXA+diu0eSvRWHsePHzdf+g4du7NlyxZJSkpy7VuyZEm66fnZqVurVq1My8eUKVM89uusMw1W7u//V+j76AKZH3/8sWufzhCbPHmyGdP14IMPZvucukyAzujSGYN6nrQ0fOnMLm0VzG5XnM5001ZCd9OmTct2HYG8goUZgVxKBwNr64N+6Z44ccKEIZ3Kri0RulK1rglzNTptXb8MW7dubcrr+jn6Zajr2ThrzGg40cHX06dPN+NvNITUr1//qmNJrkVXV9Zz60Bsra9O1dduPfcp3DqmSYOSTo/X6eK//PKLaR1xH+Sc3bo98sgjZkmA119/3YxX0rWBNGDogHJd2yftua+XLgGgawbplHNdn0lbvvRadCkDvdbsDox2aODRz0EHZ3/22WdmuQRt4dHVqRctWmT+DugYsOzSz3r06NHmURf41L8PP//883XVEcgLCERALjVkyBDzqAObNWzUrFnTfPFq4LjWl6+uy6PhYNasWeZGoNpaoC0YulaNrp3jzJDSRQV1BWydYaTBS++ndb2BSBdl1LFKujaOthRpd52GMF3U0aHdfBoAtBtPw4p+UWsLkc4Ic5edumnXoAZE/by09UbLaVjRdYLSnvev0DE2uvCi3iJF66YzunS2lb5fRotNZpV+Php+dS0hPa+2AOp6QDpQXBfi/Oijj8wA9+zSz+PkyZMmtOmAem0p0/cpVarUddcVyM38dO69tysBAADgTYwhAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHusQZYGuBqtL/+vaLjl9OwMAAHBj6MpCuu6ZrtuV9sbLaRGIskDDkC6hDwAAch+9/Y+uxJ8ZAlEWOKv+6geq9wACAAC+T1eM1waNrNw6h0CUBU43mYYhAhEAALlLVoa7MKgaAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoB3q4ARI4cOSKnTp3ydjUAa5UoUUIqVqzo7WoA8CICkQ+EoapVI+TChf95uyqAtUJCCsi+fXsJRYDFCERepi1DGobqdx0qoWUrebs6gHUSjx+W72cNN/8WCUSAvQhEPkLDULGKVbxdDQAArMSgagAAYD0CEQAAsB6BCAAAWI9ABAAArOfVQDRs2DDx8/Pz2KpWreo6fvHiRenVq5cUL15cChUqJO3atZMTJ06km7beunVrKVCggJQqVUoGDBggly9f9iizfv16qVOnjgQFBUnlypVlzpw5N+0aAQCA7/N6C1H16tXl+PHjru3bb791HevXr5989dVXsmjRItmwYYMcO3ZM2rZt6zqekpJiwlBSUpJs2rRJ5s6da8LOkCFDXGUOHTpkyjRu3FhiY2Olb9++0r17d1mxYsVNv1YAAOCbvD7tPiAgQMqUKZNu/5kzZ2TmzJkyf/58adKkidk3e/ZsiYiIkC1btkiDBg1k5cqVsmfPHlm9erWULl1aIiMjZeTIkTJo0CDT+hQYGCjTp0+X8PBwGTt2rDmHvl5D1/jx4yUqKuqmXy8AAPA9Xm8hOnDggJQrV05uu+026dixo+kCUzExMZKcnCzNmjVzldXuNF04bfPmzea5PtasWdOEIYeGnMTERNm9e7erjPs5nDLOOTJy6dIlcw73DQAA5F1eDUT169c3XVzLly+Xd99913Rv3X///XL27FmJi4szLTxFihTxeI2GHz2m9NE9DDnHnWOZldGQc+HChQzrNWrUKClcuLBrq1ChQo5eNwAA8C1e7TJr2bKl6+datWqZgBQWFiYLFy6UkJAQr9UrOjpa+vfv73qu4YlQBABA3uX1LjN32hp05513ysGDB824Ih0snZCQ4FFGZ5k5Y470Me2sM+f5tcqEhoZeNXTpbDQ97r4BAIC8y6cC0blz5+SXX36RsmXLSt26dSV//vyyZs0a1/H9+/ebMUYNGzY0z/Vx165dEh8f7yqzatUqE2CqVavmKuN+DqeMcw4AAACvBqLXXnvNTKc/fPiwmTb/2GOPSb58+aRDhw5m7E63bt1M19W6devMIOsuXbqYIKMzzFSLFi1M8OnUqZP8+OOPZir94MGDzdpF2sqjevToIb/++qsMHDhQ9u3bJ9OmTTNdcjqlHwAAwOtjiH777TcTfv744w8pWbKk3HfffWZKvf6sdGq8v7+/WZBRZ37p7DANNA4NT0uWLJGePXuaoFSwYEHp3LmzjBgxwlVGp9wvXbrUBKCJEydK+fLlZcaMGUy5BwAAvhGIFixYkOnx4OBgmTp1qtmuRgdhL1u2LNPzNGrUSHbs2HHd9QQAAHmbT40hAgAA8AYCEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoEIgAAYD0CEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoEIgAAYD0CEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPZ8JRKNHjxY/Pz/p27eva9/FixelV69eUrx4cSlUqJC0a9dOTpw44fG6I0eOSOvWraVAgQJSqlQpGTBggFy+fNmjzPr166VOnToSFBQklStXljlz5ty06wIAAL7PJwLR1q1b5b333pNatWp57O/Xr5989dVXsmjRItmwYYMcO3ZM2rZt6zqekpJiwlBSUpJs2rRJ5s6da8LOkCFDXGUOHTpkyjRu3FhiY2NN4OrevbusWLHipl4jAADwXV4PROfOnZOOHTvKBx98IEWLFnXtP3PmjMycOVPGjRsnTZo0kbp168rs2bNN8NmyZYsps3LlStmzZ4/MmzdPIiMjpWXLljJy5EiZOnWqCUlq+vTpEh4eLmPHjpWIiAjp3bu3PP744zJ+/HivXTMAAPAtXg9E2iWmLTjNmjXz2B8TEyPJycke+6tWrSoVK1aUzZs3m+f6WLNmTSldurSrTFRUlCQmJsru3btdZdKeW8s458jIpUuXzDncNwAAkHcFePPNFyxYINu3bzddZmnFxcVJYGCgFClSxGO/hh895pRxD0POcedYZmU05Fy4cEFCQkLSvfeoUaNk+PDhOXCFAAAgN/BaC9HRo0fllVdekY8++kiCg4PFl0RHR5suO2fTugIAgLzLa4FIu8Ti4+PN7K+AgACz6cDpSZMmmZ+1FUfHASUkJHi8TmeZlSlTxvysj2lnnTnPr1UmNDQ0w9YhpbPR9Lj7BgAA8i6vBaKmTZvKrl27zMwvZ6tXr54ZYO38nD9/flmzZo3rNfv37zfT7Bs2bGie66OeQ4OVY9WqVSbAVKtWzVXG/RxOGeccAAAAXhtDdMstt0iNGjU89hUsWNCsOeTs79atm/Tv31+KFStmQk6fPn1MkGnQoIE53qJFCxN8OnXqJGPGjDHjhQYPHmwGamsrj+rRo4dMmTJFBg4cKF27dpW1a9fKwoULZenSpV64agAA4Iu8Oqj6WnRqvL+/v1mQUWd+6eywadOmuY7ny5dPlixZIj179jRBSQNV586dZcSIEa4yOuVew4+uaTRx4kQpX768zJgxw5wLAADA5wKRrijtTgdb65pCul1NWFiYLFu2LNPzNmrUSHbs2JFj9QQAAHmL19chAgAA8DYCEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoEIgAAYD0CEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoEIgAAYD0CEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPa8GonfffVdq1aoloaGhZmvYsKF8/fXXruMXL16UXr16SfHixaVQoULSrl07OXHihMc5jhw5Iq1bt5YCBQpIqVKlZMCAAXL58mWPMuvXr5c6depIUFCQVK5cWebMmXPTrhEAAPg+rwai8uXLy+jRoyUmJka2bdsmTZo0kUcffVR2795tjvfr10+++uorWbRokWzYsEGOHTsmbdu2db0+JSXFhKGkpCTZtGmTzJ0714SdIUOGuMocOnTIlGncuLHExsZK3759pXv37rJixQqvXDMAAPA9fqmpqaniQ4oVKyZvv/22PP7441KyZEmZP3+++Vnt27dPIiIiZPPmzdKgQQPTmvTwww+boFS6dGlTZvr06TJo0CA5efKkBAYGmp+XLl0qP/30k+s92rdvLwkJCbJ8+fIs1SkxMVEKFy4sZ86cMS1ZOWn79u1St25daf76bClWsUqOnhvAtZ0+sl9W/bOL+cVMW5IB5B3Z+f72mTFE2tqzYMECOX/+vOk60/+ckpOTpVmzZq4yVatWlYoVK5pApPSxZs2arjCkoqKizAfgtDJpGfdzOGWcc2Tk0qVL5hzuGwAAyLu8Hoh27dplxgfp+J4ePXrI559/LtWqVZO4uDjTwlOkSBGP8hp+9JjSR/cw5Bx3jmVWRkPOhQsXMqzTqFGjTKJ0tgoVKuToNQMAAN/i9UBUpUoVM7bn+++/l549e0rnzp1lz549Xq1TdHS0aV5ztqNHj3q1PgAAwAcD0W233SZ//PFHuv06LkePZYe2AunMLx1Hoy0ztWvXlokTJ0qZMmXMYGk9pzudZabHlD6mnXXmPL9WGe1LDAkJybBO2lrlzHxzNgAAkHddVyA6fPiwGfOT0dib33///S9V6MqVK+Y8GpDy588va9ascR3bv3+/mWavY4yUPmqXW3x8vKvMqlWrTIDRbjenjPs5nDLOOQAAAAKyU/jLL790/azT1nV8jUMDkgaPSpUqZatrqmXLlmag9NmzZ82MMl0zyDl3t27dpH///mbmmYacPn36mCCjM8xUixYtTPDp1KmTjBkzxowXGjx4sFm7SFt5lI5LmjJligwcOFC6du0qa9eulYULF5qZZwAAANkORG3atDGPfn5+ZqyPO23N0TA0duzYLJ9PW3aeffZZOX78uAlAukijhqHmzZub4+PHjxd/f3+zIKO2GunssGnTprleny9fPlmyZIkZe6RBqWDBgqZeI0aMcJUJDw834UfXNNKuOF37aMaMGeZcAAAA2Q5E2p3lhIytW7dKiRIl/tKnOHPmzEyPBwcHy9SpU812NWFhYbJs2bJMz9OoUSPZsWPHddcTAADkbdkKRO6rPwMAAFgdiJSOF9JNu72cliPHrFmzcqJuAAAAvhuIhg8fbsbp1KtXT8qWLWvGFAEAAFgViPR+YXoTVZ3dBQAAYOU6RLpg4t/+9recrw0AAEBuCUTdu3c3awYBAABY22V28eJFef/992X16tVm7SBdg8jduHHjcqp+AAAAvhmIdu7cKZGRkebnn376yeMYA6wBAIAVgWjdunU5XxMAAIDcNIYIAABAbG8haty4caZdY3oDVQAAgDwdiJzxQ47k5GSJjY0144nS3vQVAAAgTwYivQt9RoYNGybnzp37q3UCAADIvWOInnnmGe5jBgAA7A5EmzdvluDg4Jw8JQAAgG92mbVt29bjeWpqqhw/fly2bdsmb7zxRk7VDQAAwHcDUeHChT2e+/v7S5UqVWTEiBHSokWLnKobAACA7wai2bNn53xNAAAAclMgcsTExMjevXvNz9WrV5e77rorp+oFAADg24EoPj5e2rdvL+vXr5ciRYqYfQkJCWbBxgULFkjJkiVzup4AAAC+NcusT58+cvbsWdm9e7ecPn3abLooY2Jiorz88ss5X0sAAABfayFavny5rF69WiIiIlz7qlWrJlOnTmVQNQAAsKOF6MqVK5I/f/50+3WfHgMAAMjzgahJkybyyiuvyLFjx1z7fv/9d+nXr580bdo0J+sHAADgm4FoypQpZrxQpUqV5PbbbzdbeHi42Td58uScryUAAICvjSGqUKGCbN++3Ywj2rdvn9mn44maNWuW0/UDAADwrRaitWvXmsHT2hLk5+cnzZs3NzPOdLv77rvNWkTffPPNjastAACAtwPRhAkT5Pnnn5fQ0NAMb+fx4osvyrhx43KyfgAAAL4ViH788Ud56KGHrnpcp9zr6tUAAAB5NhCdOHEiw+n2joCAADl58mRO1AsAAMA3A9Gtt95qVqS+mp07d0rZsmVzol4AAAC+GYhatWolb7zxhly8eDHdsQsXLsjQoUPl4Ycfzsn6AQAA+Na0+8GDB8tnn30md955p/Tu3VuqVKli9uvUe71tR0pKirz++us3qq4AAADeD0SlS5eWTZs2Sc+ePSU6OlpSU1PNfp2CHxUVZUKRlgEAAMjTCzOGhYXJsmXL5M8//5SDBw+aUHTHHXdI0aJFb0wNAQAAfHGlaqUBSBdjBAAAsPJeZgAAAHkJgQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoEIgAAYD0CEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADreTUQjRo1Su6++2655ZZbpFSpUtKmTRvZv3+/R5mLFy9Kr169pHjx4lKoUCFp166dnDhxwqPMkSNHpHXr1lKgQAFzngEDBsjly5c9yqxfv17q1KkjQUFBUrlyZZkzZ85NuUYAAOD7vBqINmzYYMLOli1bZNWqVZKcnCwtWrSQ8+fPu8r069dPvvrqK1m0aJEpf+zYMWnbtq3reEpKiglDSUlJsmnTJpk7d64JO0OGDHGVOXTokCnTuHFjiY2Nlb59+0r37t1lxYoVN/2aAQCA7wnw5psvX77c47kGGW3hiYmJkQceeEDOnDkjM2fOlPnz50uTJk1MmdmzZ0tERIQJUQ0aNJCVK1fKnj17ZPXq1VK6dGmJjIyUkSNHyqBBg2TYsGESGBgo06dPl/DwcBk7dqw5h77+22+/lfHjx0tUVJRXrh0AAPgOnxpDpAFIFStWzDxqMNJWo2bNmrnKVK1aVSpWrCibN282z/WxZs2aJgw5NOQkJibK7t27XWXcz+GUcc6R1qVLl8zr3TcAAJB3+UwgunLliunKuvfee6VGjRpmX1xcnGnhKVKkiEdZDT96zCnjHoac486xzMpo0Llw4UKGY5sKFy7s2ipUqJDDVwsAAHyJzwQiHUv0008/yYIFC7xdFYmOjjatVc529OhRb1cJAADk1TFEjt69e8uSJUtk48aNUr58edf+MmXKmMHSCQkJHq1EOstMjzllfvjhB4/zObPQ3MuknZmmz0NDQyUkJCRdfXQmmm4AAMAOXm0hSk1NNWHo888/l7Vr15qBz+7q1q0r+fPnlzVr1rj26bR8nWbfsGFD81wfd+3aJfHx8a4yOmNNw061atVcZdzP4ZRxzgEAAOwW4O1uMp1B9sUXX5i1iJwxPzpuR1tu9LFbt27Sv39/M9BaQ06fPn1MkNEZZkqn6Wvw6dSpk4wZM8acY/DgwebcTitPjx49ZMqUKTJw4EDp2rWrCV8LFy6UpUuXevPyAQCAj/BqC9G7775rxug0atRIypYt69o+/vhjVxmdGv/www+bBRl1Kr52f3322Weu4/ny5TPdbfqoQemZZ56RZ599VkaMGOEqoy1PGn60Vah27dpm+v2MGTOYcg8AALzfQqRdZtcSHBwsU6dONdvVhIWFybJlyzI9j4auHTt2XFc9AQBA3uYzs8wAAACsnmUGAN62d+9eb1cBsFqJEiXMwsveQiACYLULZ/4QET8z/hCA94SEFJB9+/Z6LRQRiABYLfl/Z3VEo0Q+PUhKhlf1dnUAKyUePyzfzxoup06dIhABgDcVKlVRilWs4u1qAPASBlUDAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoEIgAAYD0CEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoEIgAAYD0CEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9rwaijRs3yiOPPCLlypUTPz8/Wbx4scfx1NRUGTJkiJQtW1ZCQkKkWbNmcuDAAY8yp0+flo4dO0poaKgUKVJEunXrJufOnfMos3PnTrn//vslODhYKlSoIGPGjLkp1wcAAHIHrwai8+fPS+3atWXq1KkZHtfgMmnSJJk+fbp8//33UrBgQYmKipKLFy+6ymgY2r17t6xatUqWLFliQtYLL7zgOp6YmCgtWrSQsLAwiYmJkbfffluGDRsm77///k25RgAA4PsCvPnmLVu2NFtGtHVowoQJMnjwYHn00UfNvg8//FBKly5tWpLat28ve/fuleXLl8vWrVulXr16pszkyZOlVatW8s4775iWp48++kiSkpJk1qxZEhgYKNWrV5fY2FgZN26cR3ACAAD28tkxRIcOHZK4uDjTTeYoXLiw1K9fXzZv3mye66N2kzlhSGl5f39/06LklHnggQdMGHJoK9P+/fvlzz//vKnXBAAAfJNXW4gyo2FIaYuQO33uHNPHUqVKeRwPCAiQYsWKeZQJDw9Pdw7nWNGiRdO996VLl8zm3u0GAADyLp9tIfKmUaNGmdYoZ9OB2AAAIO/y2UBUpkwZ83jixAmP/frcOaaP8fHxHscvX75sZp65l8noHO7vkVZ0dLScOXPGtR09ejQHrwwAAPganw1E2s2lgWXNmjUeXVc6Nqhhw4bmuT4mJCSY2WOOtWvXypUrV8xYI6eMzjxLTk52ldEZaVWqVMmwu0wFBQWZafzuGwAAyLu8Goh0vSCd8aWbM5Bafz5y5IhZl6hv377y5ptvypdffim7du2SZ5991swca9OmjSkfEREhDz30kDz//PPyww8/yHfffSe9e/c2M9C0nHr66afNgGpdn0in53/88ccyceJE6d+/vzcvHQAA+BCvDqretm2bNG7c2PXcCSmdO3eWOXPmyMCBA81aRTo9XluC7rvvPjPNXhdYdOi0eg1BTZs2NbPL2rVrZ9YucugYoJUrV0qvXr2kbt26UqJECbPYI1PuAQCATwSiRo0amfWGrkZbiUaMGGG2q9EZZfPnz8/0fWrVqiXffPPNX6orAADIu3x2DBEAAMDNQiACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoEIgAAYD0CEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAANYjEAEAAOsRiAAAgPUIRAAAwHoEIgAAYD0CEQAAsB6BCAAAWI9ABAAArEcgAgAA1iMQAQAA6xGIAACA9QhEAADAegQiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxnVSCaOnWqVKpUSYKDg6V+/fryww8/eLtKAADAB1gTiD7++GPp37+/DB06VLZv3y61a9eWqKgoiY+P93bVAACAl1kTiMaNGyfPP/+8dOnSRapVqybTp0+XAgUKyKxZs7xdNQAA4GVWBKKkpCSJiYmRZs2aufb5+/ub55s3b/Zq3QAAgPcFiAVOnTolKSkpUrp0aY/9+nzfvn3pyl+6dMlsjjNnzpjHxMTEHK/buXPnzOPp/+6Xy5cu5Pj5AWQu8fh/zeOZ3w9I/gA/b1cHsFJi3BHXd2JOftc650pNTb1mWSsCUXaNGjVKhg8fnm5/hQoVbth7xswbfcPODeDadi2a4O0qANZ78MEHb8h5z549K4ULF860jBWBqESJEpIvXz45ceKEx359XqZMmXTlo6OjzQBsx5UrV+T06dNSvHhx8fPjN0ik/w1Ew/LRo0clNDTU29UBrMO/QVyNtgxpGCpXrpxcixWBKDAwUOrWrStr1qyRNm3auEKOPu/du3e68kFBQWZzV6RIkZtWX+RO+h8x/xkD3sO/QWTkWi1DVgUipS0+nTt3lnr16sk999wjEyZMkPPnz5tZZwAAwG7WBKKnnnpKTp48KUOGDJG4uDiJjIyU5cuXpxtoDQAA7GNNIFLaPZZRFxnwV2j3qi74mbabFcDNwb9B5AS/1KzMRQMAAMjDrFiYEQAAIDMEIgAAYD0CEQAAsB6BCAAAWI9ABGTBc889Z1YpHz3a8xYrixcvZvVy4AbROT96E+6oqKh0x6ZNm2YWzP3tt9+8UjfkPQQiIIuCg4PlX//6l/z555/ergpgBf1lY/bs2fL999/Le++959p/6NAhGThwoEyePFnKly/v1Toi7yAQAVmkv6nqve/05r9X8+mnn0r16tXNeiiVKlWSsWPH3tQ6AnmN3qNs4sSJ8tprr5kgpK1G3bp1kxYtWshdd90lLVu2lEKFCplFdjt16iSnTp1yvfaTTz6RmjVrSkhIiLkXpf4b1jsUABkhEAFZpDcIfuutt8xvpRk108fExMiTTz4p7du3l127dsmwYcPkjTfekDlz5nilvkBeobddatq0qXTt2lWmTJkiP/30k2kxatKkiQlF27ZtM3ce0Bt2679Bdfz4cenQoYN5zd69e2X9+vXStm1bE6iAjLAwI5DFMUQJCQlmzFDDhg2lWrVqMnPmTPP8scceM//JduzY0dweZuXKla7XabP+0qVLZffu3V6tP5DbxcfHm9bX06dPm5ZYDUXffPONrFixwlVGf1HRFqX9+/fLuXPnzE29Dx8+LGFhYV6tO3IHWoiAbNJxRHPnzjW/dbrT5/fee6/HPn1+4MABSUlJucm1BPKWUqVKyYsvvigRERHSpk0b+fHHH2XdunWmu8zZqlatasr+8ssvUrt2bdOqpF1mTzzxhHzwwQeM/0OmCERANj3wwANm1kt0dLS3qwJYJSAgwGxKW4AeeeQRiY2N9dj0FxD9N6pd3KtWrZKvv/7atOhqV3eVKlXMOCRAbL+5K5BTdPp9ZGSk+Q/Wob+5fvfddx7l9Pmdd95p/nMGkHPq1Kljus508oITkjKapaattLoNGTLEdJ19/vnn0r9//5teX/g+WoiA66DN8DpmaNKkSa59r776qqxZs0ZGjhwpP//8s+lW0wGgOjsGQM7q1auXGU+kA6e3bt1qusl0PFGXLl1MF7VO1ddJEDrg+siRI/LZZ5+ZMX76iwuQEQIRcJ1GjBghV65c8fiNdeHChbJgwQKpUaOG+Y1Uy+iAbAA5q1y5cqYFVsOPTsHXX1L69u1rFmv09/eX0NBQ2bhxo7Rq1cq00g4ePNgsg6HT9IGMMMsMAABYjxYiAABgPQIRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQA8iy9dcPixYu9XQ0AuQCBCECuFRcXJ3369JHbbrtNgoKCpEKFCuaGn3oLFQDIDm7uCiBXOnz4sLlpp96q4e233za3bkhOTjb3s9L7XO3bt++GvG9SUpIEBgbekHMD8B5aiADkSi+99JLpEvvhhx+kXbt25n5V1atXN3cy37Jli6vcqVOn5LHHHpMCBQrIHXfcIV9++aXr2Jw5c0ygcqddbHpex7BhwyQyMlJmzJgh4eHhEhwcbPZrGd13tXMDyF0IRAByHb3L+fLly01LUMGCBdMddw85w4cPlyeffFJ27txpbvTZsWNH8/rsOHjwoHz66afmjumxsbE5em4AvoFABCDX0YCi96WuWrXqNcs+99xz0qFDB6lcubK89dZbcu7cOdOqlN1usg8//FDuuusuqVWrVo6eG4BvIBAByHU0DGWVe4DR1qTQ0FCJj4/P1vuFhYVJyZIlb8i5AfgGAhGAXEfH6+gYnqwMnM6fP7/Hc33dlStXzM/+/v7pwpUOzE4ro265a50bQO5CIAKQ6xQrVkyioqJk6tSpcv78+XTHExISsnQebfU5e/asxzncxwgBsAeBCECupGEoJSVF7rnnHjPg+cCBA7J3716ZNGmSNGzYMEvnqF+/vpkh9o9//EN++eUXmT9/vpl5BsA+BCIAuZIuxrh9+3Zp3LixvPrqq1KjRg1p3ry5WZTx3XffzXJL07x582TZsmVmHaP//Oc/Zpo9APv4pWZndCIAAEAeRAsRAACwHoEIAABYj0AEAACsRyACAADWIxABAADrEYgAAID1CEQAAMB6BCIAAGA9AhEAALAegQgAAFiPQAQAAKxHIAIAAGK7/weEar7KvSXFugAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "total = len(df['Churn'])\n",
    "x,y = df['Churn'].value_counts()\n",
    "print(f\"Total: {total}\")\n",
    "print(f\"Yes: {(x/total)*100:.2f}%, {x}\")\n",
    "print(f\" No: {(y/total)*100:.2f}%, {y}\")\n",
    "sns.histplot(data=df, x='Churn')\n",
    "plt.title(\"Distribution of Churn\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "97f0e74c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MultipleLines\n",
      "No     4065\n",
      "Yes    2967\n",
      "Name: count, dtype: int64\n",
      "PhoneService\n",
      "Yes    6352\n",
      "No      680\n",
      "Name: count, dtype: int64\n",
      "InternetService\n",
      "Fiber optic    3096\n",
      "DSL            2416\n",
      "No             1520\n",
      "Name: count, dtype: int64\n",
      "OnlineSecurity\n",
      "No     5017\n",
      "Yes    2015\n",
      "Name: count, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(df[\"MultipleLines\"].value_counts())\n",
    "print(df[\"PhoneService\"].value_counts())\n",
    "print(df[\"InternetService\"].value_counts())\n",
    "print(df[\"OnlineSecurity\"].value_counts())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
